name: Release

on:
  push:
    tags:
      - 'v*'

permissions: write-all

jobs:
  release-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@figureland'

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test the package
        run: bun run test

      - name: Publish to GitHub Packages
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Test the package
        run: bun run test

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@figureland'

      - name: Publish to npmjs.com
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  # release-jsr:
  #   runs-on: ubuntu-latest

  #   permissions:
  #     contents: read
  #     id-token: write

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20.x'
  #         registry-url: 'https://npm.pkg.github.com/'
  #         scope: '@figureland'

  #     - uses: oven-sh/setup-bun@v1

  #     - name: Install dependencies
  #       run: bun install

  #     - name: Test the package
  #       run: bun run test

  #     - name: Publish package
  #       run: npx jsr publish
