name: Update Dependencies

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Create new branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          BRANCH_NAME="dependencies/update-$(date +'%Y-%m-%d')"
          git checkout -b $BRANCH_NAME
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Update dependencies
        run: bun update

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet bun.lockb; then
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          fi

      - name: Run tests to verify updates
        if: env.CHANGES_DETECTED == 'true'
        run: bun test

      - name: Commit changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          git add bun.lockb package.json
          git commit -m "chore: update dependencies $(date +'%Y-%m-%d')"
          git push origin $BRANCH_NAME

      - name: Create Pull Request
        if: env.CHANGES_DETECTED == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "chore: update dependencies $(date +'%Y-%m-%d')" \
            --body "This PR updates the project dependencies via \`bun update\`.

          ## Changes
          - Updated dependencies to their latest compatible versions
          - Verified changes with tests

          This PR was automatically generated by the update-dependencies workflow." \
            --base main \
            --head $BRANCH_NAME
